# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'adv4.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1012, 710)
        MainWindow.setMinimumSize(QtCore.QSize(1012, 710))
        MainWindow.setMaximumSize(QtCore.QSize(1012, 710))
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.background1 = QtWidgets.QWidget(self.centralwidget)
        self.background1.setGeometry(QtCore.QRect(20, 10, 641, 361))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setBold(True)
        font.setWeight(75)
        self.background1.setFont(font)
        self.background1.setStyleSheet("background-color: rgb(221, 221, 221)")
        self.background1.setObjectName("background1")
        self.detector_background = QtWidgets.QWidget(self.background1)
        self.detector_background.setGeometry(QtCore.QRect(0, 20, 641, 51))
        self.detector_background.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.detector_background.setAutoFillBackground(False)
        self.detector_background.setStyleSheet("QWidget {\n"
"    background-color: #ffc355; /* cor de fundo amarela */\n"
"    /*border-radius: 10px;*/\n"
"\n"
"}\n"
"")
        self.detector_background.setObjectName("detector_background")
        self.detector_label = QtWidgets.QLabel(self.detector_background)
        self.detector_label.setGeometry(QtCore.QRect(260, 10, 120, 30))
        self.detector_label.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.detector_label.setFont(font)
        self.detector_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.detector_label.setStyleSheet("QLabel {\n"
"    border: none;\n"
"}\n"
"")
        self.detector_label.setAlignment(QtCore.Qt.AlignCenter)
        self.detector_label.setWordWrap(False)
        self.detector_label.setObjectName("detector_label")
        self.acquire_mode = QtWidgets.QLabel(self.background1)
        self.acquire_mode.setGeometry(QtCore.QRect(50, 170, 150, 30))
        self.acquire_mode.setMinimumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.acquire_mode.setFont(font)
        self.acquire_mode.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.acquire_mode.setStyleSheet("QLabel {\n"
"    border: none;\n"
"}\n"
"")
        self.acquire_mode.setAlignment(QtCore.Qt.AlignCenter)
        self.acquire_mode.setWordWrap(False)
        self.acquire_mode.setObjectName("acquire_mode")
        self.input_exposures = QtWidgets.QSpinBox(self.background1)
        self.input_exposures.setGeometry(QtCore.QRect(50, 120, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.input_exposures.setFont(font)
        self.input_exposures.setStyleSheet("QSpinBox {\n"
"    background-color: rgb(238, 238, 238);\n"
"    border: 1px solid #a9a9a9;\n"
"    border-radius: 5px; \n"
"    padding: 1px 3px; \n"
"}\n"
"\n"
"\n"
"")
        self.input_exposures.setMinimum(-999999999)
        self.input_exposures.setMaximum(999999999)
        self.input_exposures.setObjectName("input_exposures")
        self.input_acquire = QtWidgets.QSpinBox(self.background1)
        self.input_acquire.setGeometry(QtCore.QRect(50, 210, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.input_acquire.setFont(font)
        self.input_acquire.setStyleSheet("QSpinBox {\n"
"    background-color: rgb(238, 238, 238);\n"
"    border: 1px solid #a9a9a9;\n"
"    border-radius: 5px; \n"
"    padding: 1px 3px; \n"
"}\n"
"\n"
"\n"
"")
        self.input_acquire.setMinimum(-999999999)
        self.input_acquire.setMaximum(999999999)
        self.input_acquire.setObjectName("input_acquire")
        self.exposure_count = QtWidgets.QLabel(self.background1)
        self.exposure_count.setGeometry(QtCore.QRect(50, 80, 180, 30))
        self.exposure_count.setMinimumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.exposure_count.setFont(font)
        self.exposure_count.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.exposure_count.setStyleSheet("QLabel {\n"
"    border: none;\n"
"}\n"
"")
        self.exposure_count.setAlignment(QtCore.Qt.AlignCenter)
        self.exposure_count.setWordWrap(False)
        self.exposure_count.setObjectName("exposure_count")
        self.discr_exposures = QtWidgets.QPushButton(self.background1)
        self.discr_exposures.setGeometry(QtCore.QRect(240, 80, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.discr_exposures.setFont(font)
        self.discr_exposures.setStyleSheet("QPushButton {\n"
"    border: none; /* Remove a borda */\n"
"    background-color: transparent; /* Fundo transparente */\n"
"    color: blue; /* Cor do texto em azul */\n"
"}\n"
"")
        self.discr_exposures.setObjectName("discr_exposures")
        self.discr_acquire_mode = QtWidgets.QPushButton(self.background1)
        self.discr_acquire_mode.setGeometry(QtCore.QRect(240, 170, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.discr_acquire_mode.setFont(font)
        self.discr_acquire_mode.setStyleSheet("QPushButton {\n"
"    border: none; /* Remove a borda */\n"
"    background-color: transparent; /* Fundo transparente */\n"
"    color: blue; /* Cor do texto em azul */\n"
"}\n"
"")
        self.discr_acquire_mode.setObjectName("discr_acquire_mode")
        self.discr_sensor_bias = QtWidgets.QPushButton(self.background1)
        self.discr_sensor_bias.setGeometry(QtCore.QRect(560, 80, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.discr_sensor_bias.setFont(font)
        self.discr_sensor_bias.setStyleSheet("QPushButton {\n"
"    border: none; /* Remove a borda */\n"
"    background-color: transparent; /* Fundo transparente */\n"
"    color: blue; /* Cor do texto em azul */\n"
"}\n"
"")
        self.discr_sensor_bias.setObjectName("discr_sensor_bias")
        self.sensor_bias = QtWidgets.QLabel(self.background1)
        self.sensor_bias.setGeometry(QtCore.QRect(370, 80, 130, 30))
        self.sensor_bias.setMinimumSize(QtCore.QSize(130, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.sensor_bias.setFont(font)
        self.sensor_bias.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.sensor_bias.setStyleSheet("QLabel {\n"
"    border: none;\n"
"}\n"
"")
        self.sensor_bias.setAlignment(QtCore.Qt.AlignCenter)
        self.sensor_bias.setWordWrap(False)
        self.sensor_bias.setObjectName("sensor_bias")
        self.input_sensor = QtWidgets.QSpinBox(self.background1)
        self.input_sensor.setGeometry(QtCore.QRect(370, 120, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.input_sensor.setFont(font)
        self.input_sensor.setStyleSheet("QSpinBox {\n"
"    background-color: rgb(238, 238, 238);\n"
"    border: 1px solid #a9a9a9;\n"
"    border-radius: 5px; \n"
"    padding: 1px 3px; \n"
"}\n"
"\n"
"\n"
"")
        self.input_sensor.setMinimum(-999999999)
        self.input_sensor.setMaximum(999999999)
        self.input_sensor.setObjectName("input_sensor")
        self.input_threshold = QtWidgets.QSpinBox(self.background1)
        self.input_threshold.setGeometry(QtCore.QRect(370, 300, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.input_threshold.setFont(font)
        self.input_threshold.setStyleSheet("QSpinBox {\n"
"    background-color: rgb(238, 238, 238);\n"
"    border: 1px solid #a9a9a9;\n"
"    border-radius: 5px; \n"
"    padding: 1px 3px; \n"
"}\n"
"\n"
"\n"
"")
        self.input_threshold.setMinimum(-999999999)
        self.input_threshold.setMaximum(999999999)
        self.input_threshold.setObjectName("input_threshold")
        self.gain_all = QtWidgets.QLabel(self.background1)
        self.gain_all.setGeometry(QtCore.QRect(370, 170, 90, 30))
        self.gain_all.setMinimumSize(QtCore.QSize(90, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.gain_all.setFont(font)
        self.gain_all.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.gain_all.setStyleSheet("QLabel {\n"
"    border: none;\n"
"}\n"
"")
        self.gain_all.setAlignment(QtCore.Qt.AlignCenter)
        self.gain_all.setWordWrap(False)
        self.gain_all.setObjectName("gain_all")
        self.input_gain = QtWidgets.QSpinBox(self.background1)
        self.input_gain.setGeometry(QtCore.QRect(370, 210, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.input_gain.setFont(font)
        self.input_gain.setStyleSheet("QSpinBox {\n"
"    background-color: rgb(238, 238, 238);\n"
"    border: 1px solid #a9a9a9;\n"
"    border-radius: 5px; \n"
"    padding: 1px 3px; \n"
"}\n"
"\n"
"\n"
"")
        self.input_gain.setMinimum(-999999999)
        self.input_gain.setMaximum(999999999)
        self.input_gain.setObjectName("input_gain")
        self.discr_threshold = QtWidgets.QPushButton(self.background1)
        self.discr_threshold.setGeometry(QtCore.QRect(560, 260, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.discr_threshold.setFont(font)
        self.discr_threshold.setStyleSheet("QPushButton {\n"
"    border: none; /* Remove a borda */\n"
"    background-color: transparent; /* Fundo transparente */\n"
"    color: blue; /* Cor do texto em azul */\n"
"}\n"
"")
        self.discr_threshold.setObjectName("discr_threshold")
        self.discr_gain_all = QtWidgets.QPushButton(self.background1)
        self.discr_gain_all.setGeometry(QtCore.QRect(560, 170, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.discr_gain_all.setFont(font)
        self.discr_gain_all.setStyleSheet("QPushButton {\n"
"    border: none; /* Remove a borda */\n"
"    background-color: transparent; /* Fundo transparente */\n"
"    color: blue; /* Cor do texto em azul */\n"
"}\n"
"")
        self.discr_gain_all.setObjectName("discr_gain_all")
        self.threshold = QtWidgets.QLabel(self.background1)
        self.threshold.setGeometry(QtCore.QRect(370, 260, 110, 35))
        self.threshold.setMinimumSize(QtCore.QSize(110, 35))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.threshold.setFont(font)
        self.threshold.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.threshold.setStyleSheet("QLabel {\n"
"    border: none;\n"
"}\n"
"")
        self.threshold.setAlignment(QtCore.Qt.AlignCenter)
        self.threshold.setWordWrap(False)
        self.threshold.setObjectName("threshold")
        self.discr_trigger_mode = QtWidgets.QPushButton(self.background1)
        self.discr_trigger_mode.setGeometry(QtCore.QRect(240, 260, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.discr_trigger_mode.setFont(font)
        self.discr_trigger_mode.setStyleSheet("QPushButton {\n"
"    border: none; /* Remove a borda */\n"
"    background-color: transparent; /* Fundo transparente */\n"
"    color: blue; /* Cor do texto em azul */\n"
"}\n"
"")
        self.discr_trigger_mode.setObjectName("discr_trigger_mode")
        self.trigger_mode = QtWidgets.QLabel(self.background1)
        self.trigger_mode.setGeometry(QtCore.QRect(50, 260, 145, 35))
        self.trigger_mode.setMinimumSize(QtCore.QSize(145, 35))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.trigger_mode.setFont(font)
        self.trigger_mode.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.trigger_mode.setStyleSheet("QLabel {\n"
"    border: none;\n"
"}\n"
"")
        self.trigger_mode.setAlignment(QtCore.Qt.AlignCenter)
        self.trigger_mode.setWordWrap(False)
        self.trigger_mode.setObjectName("trigger_mode")
        self.input_trigger = QtWidgets.QSpinBox(self.background1)
        self.input_trigger.setGeometry(QtCore.QRect(50, 300, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.input_trigger.setFont(font)
        self.input_trigger.setStyleSheet("QSpinBox {\n"
"    background-color: rgb(238, 238, 238);\n"
"    border: 1px solid #a9a9a9;\n"
"    border-radius: 5px; \n"
"    padding: 1px 3px; \n"
"}\n"
"\n"
"\n"
"")
        self.input_trigger.setMinimum(-999999999)
        self.input_trigger.setMaximum(999999999)
        self.input_trigger.setObjectName("input_trigger")
        self.background2 = QtWidgets.QWidget(self.centralwidget)
        self.background2.setGeometry(QtCore.QRect(20, 380, 641, 271))
        self.background2.setStyleSheet("background-color: rgb(221, 221, 221)")
        self.background2.setObjectName("background2")
        self.discr_micro_z = QtWidgets.QPushButton(self.background2)
        self.discr_micro_z.setGeometry(QtCore.QRect(560, 120, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.discr_micro_z.setFont(font)
        self.discr_micro_z.setStyleSheet("QPushButton {\n"
"    border: none; /* Remove a borda */\n"
"    background-color: transparent; /* Fundo transparente */\n"
"    color: blue; /* Cor do texto em azul */\n"
"}\n"
"")
        self.discr_micro_z.setObjectName("discr_micro_z")
        self.micro_step_angular = QtWidgets.QLabel(self.background2)
        self.micro_step_angular.setGeometry(QtCore.QRect(50, 120, 181, 35))
        self.micro_step_angular.setMinimumSize(QtCore.QSize(130, 35))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.micro_step_angular.setFont(font)
        self.micro_step_angular.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.micro_step_angular.setStyleSheet("QLabel {\n"
"    border: none;\n"
"}\n"
"")
        self.micro_step_angular.setAlignment(QtCore.Qt.AlignCenter)
        self.micro_step_angular.setWordWrap(False)
        self.micro_step_angular.setObjectName("micro_step_angular")
        self.discr_micro_ang = QtWidgets.QPushButton(self.background2)
        self.discr_micro_ang.setGeometry(QtCore.QRect(240, 120, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.discr_micro_ang.setFont(font)
        self.discr_micro_ang.setStyleSheet("QPushButton {\n"
"    border: none; /* Remove a borda */\n"
"    background-color: transparent; /* Fundo transparente */\n"
"    color: blue; /* Cor do texto em azul */\n"
"}\n"
"")
        self.discr_micro_ang.setObjectName("discr_micro_ang")
        self.input_microang = QtWidgets.QSpinBox(self.background2)
        self.input_microang.setGeometry(QtCore.QRect(50, 160, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.input_microang.setFont(font)
        self.input_microang.setStyleSheet("QSpinBox {\n"
"    background-color: rgb(238, 238, 238);\n"
"    border: 1px solid #a9a9a9;\n"
"    border-radius: 5px; \n"
"    padding: 1px 3px; \n"
"}\n"
"\n"
"\n"
"")
        self.input_microang.setMinimum(-999999999)
        self.input_microang.setMaximum(999999999)
        self.input_microang.setObjectName("input_microang")
        self.input_microz = QtWidgets.QSpinBox(self.background2)
        self.input_microz.setGeometry(QtCore.QRect(370, 160, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.input_microz.setFont(font)
        self.input_microz.setStyleSheet("QSpinBox {\n"
"    background-color: rgb(238, 238, 238);\n"
"    border: 1px solid #a9a9a9;\n"
"    border-radius: 5px; \n"
"    padding: 1px 3px; \n"
"}\n"
"\n"
"\n"
"")
        self.input_microz.setPrefix("")
        self.input_microz.setMinimum(-999999999)
        self.input_microz.setMaximum(999999999)
        self.input_microz.setObjectName("input_microz")
        self.micro_step_z = QtWidgets.QLabel(self.background2)
        self.micro_step_z.setGeometry(QtCore.QRect(370, 120, 141, 35))
        self.micro_step_z.setMinimumSize(QtCore.QSize(130, 35))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.micro_step_z.setFont(font)
        self.micro_step_z.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.micro_step_z.setStyleSheet("QLabel {\n"
"    border: none;\n"
"}\n"
"")
        self.micro_step_z.setAlignment(QtCore.Qt.AlignCenter)
        self.micro_step_z.setWordWrap(False)
        self.micro_step_z.setObjectName("micro_step_z")
        self.mechanic_background_2 = QtWidgets.QWidget(self.background2)
        self.mechanic_background_2.setGeometry(QtCore.QRect(0, 20, 641, 51))
        self.mechanic_background_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.mechanic_background_2.setAutoFillBackground(False)
        self.mechanic_background_2.setStyleSheet("QWidget {\n"
"    background-color: #ffc355; /* cor de fundo amarela */\n"
"    /*border-radius: 10px;*/\n"
"\n"
"}\n"
"")
        self.mechanic_background_2.setObjectName("mechanic_background_2")
        self.mechanic_label_2 = QtWidgets.QLabel(self.mechanic_background_2)
        self.mechanic_label_2.setGeometry(QtCore.QRect(250, 10, 131, 30))
        self.mechanic_label_2.setMinimumSize(QtCore.QSize(130, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.mechanic_label_2.setFont(font)
        self.mechanic_label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.mechanic_label_2.setStyleSheet("QLabel {\n"
"    border: none;\n"
"}\n"
"")
        self.mechanic_label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.mechanic_label_2.setWordWrap(False)
        self.mechanic_label_2.setObjectName("mechanic_label_2")
        self.background3 = QtWidgets.QWidget(self.centralwidget)
        self.background3.setGeometry(QtCore.QRect(680, 10, 311, 641))
        self.background3.setStyleSheet("background-color: rgb(221, 221, 221)")
        self.background3.setObjectName("background3")
        self.execute_background = QtWidgets.QWidget(self.background3)
        self.execute_background.setGeometry(QtCore.QRect(0, 20, 311, 51))
        self.execute_background.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.execute_background.setAutoFillBackground(False)
        self.execute_background.setStyleSheet("QWidget {\n"
"    background-color: #ffc355; /* cor de fundo amarela */\n"
"    /*border-radius: 10px;*/\n"
"\n"
"}\n"
"")
        self.execute_background.setObjectName("execute_background")
        self.execute_label = QtWidgets.QLabel(self.execute_background)
        self.execute_label.setGeometry(QtCore.QRect(70, 10, 161, 30))
        self.execute_label.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.execute_label.setFont(font)
        self.execute_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.execute_label.setStyleSheet("QLabel {\n"
"    border: none;\n"
"}\n"
"")
        self.execute_label.setAlignment(QtCore.Qt.AlignCenter)
        self.execute_label.setWordWrap(False)
        self.execute_label.setObjectName("execute_label")
        self.download_json = QtWidgets.QPushButton(self.background3)
        self.download_json.setGeometry(QtCore.QRect(70, 250, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.download_json.setFont(font)
        self.download_json.setStyleSheet("QWidget {\n"
"    background-color: #FFB62D; /* cor de fundo amarela */\n"
"    border-radius: 10px; /* bordas arredondadas */\n"
"    border: 1px solid black; /* borda sólida preta */\n"
"}\n"
"")
        self.download_json.setObjectName("download_json")
        self.upload_json = QtWidgets.QPushButton(self.background3)
        self.upload_json.setGeometry(QtCore.QRect(70, 310, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.upload_json.setFont(font)
        self.upload_json.setStyleSheet("QWidget {\n"
"    background-color: #FFB62D; /* cor de fundo amarela */\n"
"    border-radius: 10px; /* bordas arredondadas */\n"
"    border: 1px solid black; /* borda sólida preta */\n"
"}\n"
"")
        self.upload_json.setObjectName("upload_json")
        self.clear_fields = QtWidgets.QPushButton(self.background3)
        self.clear_fields.setGeometry(QtCore.QRect(70, 520, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.clear_fields.setFont(font)
        self.clear_fields.setStyleSheet("QWidget {\n"
"    background-color: #FFB62D; /* cor de fundo amarela */\n"
"    border-radius: 10px; /* bordas arredondadas */\n"
"    border: 1px solid black; /* borda sólida preta */\n"
"}\n"
"")
        self.clear_fields.setObjectName("clear_fields")
        self.send_parameters = QtWidgets.QPushButton(self.background3)
        self.send_parameters.setGeometry(QtCore.QRect(70, 120, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.send_parameters.setFont(font)
        self.send_parameters.setStyleSheet("QWidget {\n"
"    background-color: #FFB62D; /* cor de fundo amarela */\n"
"    border-radius: 10px; /* bordas arredondadas */\n"
"    border: 1px solid black; /* borda sólida preta */\n"
"}\n"
"")
        self.send_parameters.setObjectName("send_parameters")
        self.default_json = QtWidgets.QPushButton(self.background3)
        self.default_json.setGeometry(QtCore.QRect(70, 460, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.default_json.setFont(font)
        self.default_json.setStyleSheet("QWidget {\n"
"    background-color: #FFB62D; /* cor de fundo amarela */\n"
"    border-radius: 10px; /* bordas arredondadas */\n"
"    border: 1px solid black; /* borda sólida preta */\n"
"}\n"
"")
        self.default_json.setObjectName("default_json")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1012, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Advanced Settings"))
        self.detector_label.setText(_translate("MainWindow", "Detector"))
        self.acquire_mode.setText(_translate("MainWindow", "Acquire Mode"))
        self.exposure_count.setText(_translate("MainWindow", "Exposure Count"))
        self.discr_exposures.setText(_translate("MainWindow", "?"))
        self.discr_acquire_mode.setText(_translate("MainWindow", "?"))
        self.discr_sensor_bias.setText(_translate("MainWindow", "?"))
        self.sensor_bias.setText(_translate("MainWindow", "Sensor Bias"))
        self.gain_all.setText(_translate("MainWindow", "Gain all"))
        self.discr_threshold.setText(_translate("MainWindow", "?"))
        self.discr_gain_all.setText(_translate("MainWindow", "?"))
        self.threshold.setText(_translate("MainWindow", "Threshold"))
        self.discr_trigger_mode.setText(_translate("MainWindow", "?"))
        self.trigger_mode.setText(_translate("MainWindow", "Trigger Mode"))
        self.discr_micro_z.setText(_translate("MainWindow", "?"))
        self.micro_step_angular.setText(_translate("MainWindow", "Micro step Ang."))
        self.discr_micro_ang.setText(_translate("MainWindow", "?"))
        self.micro_step_z.setText(_translate("MainWindow", "Micro step Z"))
        self.mechanic_label_2.setText(_translate("MainWindow", "Mechanic"))
        self.execute_label.setText(_translate("MainWindow", "Parameters"))
        self.download_json.setText(_translate("MainWindow", "Download"))
        self.upload_json.setText(_translate("MainWindow", "Upload"))
        self.clear_fields.setText(_translate("MainWindow", "Clear Fields"))
        self.send_parameters.setText(_translate("MainWindow", "Send "))
        self.default_json.setText(_translate("MainWindow", "Default"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
