# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'data_s3.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(574, 609)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.background2 = QtWidgets.QWidget(self.centralwidget)
        self.background2.setGeometry(QtCore.QRect(10, 10, 551, 551))
        self.background2.setStyleSheet("background-color: rgb(221, 221, 221)")
        self.background2.setObjectName("background2")
        self.commands_background = QtWidgets.QWidget(self.background2)
        self.commands_background.setGeometry(QtCore.QRect(0, 20, 551, 51))
        self.commands_background.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.commands_background.setAutoFillBackground(False)
        self.commands_background.setStyleSheet("QWidget {\n"
"    background-color: #ffc355; /* cor de fundo amarela */\n"
"    /*border-radius: 10px;*/\n"
"\n"
"}\n"
"")
        self.commands_background.setObjectName("commands_background")
        self.commands_label = QtWidgets.QLabel(self.commands_background)
        self.commands_label.setGeometry(QtCore.QRect(200, 10, 151, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.commands_label.setFont(font)
        self.commands_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.commands_label.setStyleSheet("QLabel {\n"
"    border: none;\n"
"}\n"
"")
        self.commands_label.setAlignment(QtCore.Qt.AlignCenter)
        self.commands_label.setWordWrap(False)
        self.commands_label.setObjectName("commands_label")
        self.download_table_csv = QtWidgets.QPushButton(self.background2)
        self.download_table_csv.setGeometry(QtCore.QRect(190, 420, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.download_table_csv.setFont(font)
        self.download_table_csv.setStyleSheet("QWidget {\n"
"    background-color: #FFB62D; /* cor de fundo amarela */\n"
"    border-radius: 10px; /* bordas arredondadas */\n"
"    border: 1px solid black; /* borda sólida preta */\n"
"}\n"
"")
        self.download_table_csv.setObjectName("download_table_csv")
        self.input_tabel_request = QtWidgets.QSpinBox(self.background2)
        self.input_tabel_request.setGeometry(QtCore.QRect(180, 370, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.input_tabel_request.setFont(font)
        self.input_tabel_request.setStyleSheet("QSpinBox {\n"
"    background-color: #f2f2f2; /* Cor de fundo mais clara */\n"
"    color: #000;\n"
"    border: 1px solid #c4c4c4;\n"
"    border-radius: 4px;\n"
"    padding-left: 4px;\n"
"    padding-right: 4px;\n"
"    padding-top: 2px;\n"
"    padding-bottom: 2px;\n"
"    min-width: 100px;\n"
"    min-height: 20px;\n"
"}\n"
"")
        self.input_tabel_request.setObjectName("input_tabel_request")
        self.dateEdit_Start = QtWidgets.QDateEdit(self.background2)
        self.dateEdit_Start.setGeometry(QtCore.QRect(220, 170, 110, 31))
        self.dateEdit_Start.setStyleSheet("QDateEdit {\n"
"    background-color: #f2f2f2; /* Cor de fundo mais clara */\n"
"    color: #000;\n"
"    border: 1px solid #c4c4c4;\n"
"    border-radius: 4px;\n"
"    padding-left: 4px;\n"
"    padding-right: 4px;\n"
"    padding-top: 2px;\n"
"    padding-bottom: 2px;\n"
"    min-width: 100px;\n"
"    min-height: 20px;\n"
"}\n"
"")
        self.dateEdit_Start.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(2024, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dateEdit_Start.setCalendarPopup(True)
        self.dateEdit_Start.setObjectName("dateEdit_Start")
        self.dateEdit_End = QtWidgets.QDateEdit(self.background2)
        self.dateEdit_End.setGeometry(QtCore.QRect(220, 250, 111, 31))
        self.dateEdit_End.setStyleSheet("QDateEdit {\n"
"    background-color: #f2f2f2; /* Cor de fundo mais clara */\n"
"    color: #000;\n"
"    border: 1px solid #c4c4c4;\n"
"    border-radius: 4px;\n"
"    padding-left: 4px;\n"
"    padding-right: 4px;\n"
"    padding-top: 2px;\n"
"    padding-bottom: 2px;\n"
"    min-width: 100px;\n"
"    min-height: 20px;\n"
"}\n"
"")
        self.dateEdit_End.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(2024, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dateEdit_End.setCalendarPopup(True)
        self.dateEdit_End.setObjectName("dateEdit_End")
        self.get_report_from = QtWidgets.QLabel(self.background2)
        self.get_report_from.setGeometry(QtCore.QRect(200, 120, 151, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.get_report_from.setFont(font)
        self.get_report_from.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.get_report_from.setStyleSheet("QLabel {\n"
"    border: none;\n"
"}\n"
"")
        self.get_report_from.setAlignment(QtCore.Qt.AlignCenter)
        self.get_report_from.setWordWrap(False)
        self.get_report_from.setObjectName("get_report_from")
        self.to = QtWidgets.QLabel(self.background2)
        self.to.setGeometry(QtCore.QRect(200, 210, 151, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.to.setFont(font)
        self.to.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.to.setStyleSheet("QLabel {\n"
"    border: none;\n"
"}\n"
"")
        self.to.setAlignment(QtCore.Qt.AlignCenter)
        self.to.setWordWrap(False)
        self.to.setObjectName("to")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 574, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Reports"))
        self.commands_label.setText(_translate("MainWindow", "Report"))
        self.download_table_csv.setText(_translate("MainWindow", "Download "))
        self.input_tabel_request.setSpecialValueText(_translate("MainWindow", "Report Name"))
        self.get_report_from.setText(_translate("MainWindow", "Get report from:"))
        self.to.setText(_translate("MainWindow", "to"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
