# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CT_Visualizer.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1304, 1006)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_open = QtWidgets.QPushButton(self.centralwidget)
        self.btn_open.setGeometry(QtCore.QRect(10, 80, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_open.setFont(font)
        self.btn_open.setStyleSheet("QPushButton {\n"
"    background-color: #FFB62D;\n"
"    border-radius: 10px;\n"
"    border: 1px solid black;\n"
"}\n"
" \n"
"QPushButton:hover {\n"
"    background-color: #FFA500;\n"
"}\n"
" \n"
"QPushButton:pressed {\n"
"    background-color: #FFB62D;\n"
"    padding-left: 1px;\n"
"    padding-top: 1px;\n"
"}")
        self.btn_open.setObjectName("btn_open")
        self.btn_colormap = QtWidgets.QPushButton(self.centralwidget)
        self.btn_colormap.setGeometry(QtCore.QRect(10, 120, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_colormap.setFont(font)
        self.btn_colormap.setStyleSheet("QPushButton {\n"
"    background-color: #FFB62D;\n"
"    border-radius: 10px;\n"
"    border: 1px solid black;\n"
"}\n"
" \n"
"QPushButton:hover {\n"
"    background-color: #FFA500;\n"
"}\n"
" \n"
"QPushButton:pressed {\n"
"    background-color: #FFB62D;\n"
"    padding-left: 1px;\n"
"    padding-top: 1px;\n"
"}")
        self.btn_colormap.setObjectName("btn_colormap")
        self.btn_clear = QtWidgets.QPushButton(self.centralwidget)
        self.btn_clear.setGeometry(QtCore.QRect(10, 160, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_clear.setFont(font)
        self.btn_clear.setStyleSheet("QPushButton {\n"
"    background-color: #FFB62D;\n"
"    border-radius: 10px;\n"
"    border: 1px solid black;\n"
"}\n"
" \n"
"QPushButton:hover {\n"
"    background-color: #FFA500;\n"
"}\n"
" \n"
"QPushButton:pressed {\n"
"    background-color: #FFB62D;\n"
"    padding-left: 1px;\n"
"    padding-top: 1px;\n"
"}")
        self.btn_clear.setObjectName("btn_clear")
        self.btn_rot = QtWidgets.QPushButton(self.centralwidget)
        self.btn_rot.setGeometry(QtCore.QRect(10, 200, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_rot.setFont(font)
        self.btn_rot.setStyleSheet("QPushButton {\n"
"    background-color: #FFB62D;\n"
"    border-radius: 10px;\n"
"    border: 1px solid black;\n"
"}\n"
" \n"
"QPushButton:hover {\n"
"    background-color: #FFA500;\n"
"}\n"
" \n"
"QPushButton:pressed {\n"
"    background-color: #FFB62D;\n"
"    padding-left: 1px;\n"
"    padding-top: 1px;\n"
"}")
        self.btn_rot.setObjectName("btn_rot")
        self.btn_hist = QtWidgets.QPushButton(self.centralwidget)
        self.btn_hist.setGeometry(QtCore.QRect(10, 240, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_hist.setFont(font)
        self.btn_hist.setStyleSheet("QPushButton {\n"
"    background-color: #FFB62D;\n"
"    border-radius: 10px;\n"
"    border: 1px solid black;\n"
"}\n"
" \n"
"QPushButton:hover {\n"
"    background-color: #FFA500;\n"
"}\n"
" \n"
"QPushButton:pressed {\n"
"    background-color: #FFB62D;\n"
"    padding-left: 1px;\n"
"    padding-top: 1px;\n"
"}")
        self.btn_hist.setObjectName("btn_hist")
        self.btn_flat = QtWidgets.QPushButton(self.centralwidget)
        self.btn_flat.setGeometry(QtCore.QRect(10, 280, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_flat.setFont(font)
        self.btn_flat.setStyleSheet("QPushButton {\n"
"    background-color: #FFB62D;\n"
"    border-radius: 10px;\n"
"    border: 1px solid black;\n"
"}\n"
" \n"
"QPushButton:hover {\n"
"    background-color: #FFA500;\n"
"}\n"
" \n"
"QPushButton:pressed {\n"
"    background-color: #FFB62D;\n"
"    padding-left: 1px;\n"
"    padding-top: 1px;\n"
"}")
        self.btn_flat.setObjectName("btn_flat")
        self.btn_roi1 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_roi1.setGeometry(QtCore.QRect(10, 350, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_roi1.setFont(font)
        self.btn_roi1.setStyleSheet("QPushButton {\n"
"    background-color: #FFB62D;\n"
"    border-radius: 10px;\n"
"    border: 1px solid black;\n"
"}\n"
" \n"
"QPushButton:hover {\n"
"    background-color: #FFA500;\n"
"}\n"
" \n"
"QPushButton:pressed {\n"
"    background-color: #FFB62D;\n"
"    padding-left: 1px;\n"
"    padding-top: 1px;\n"
"}")
        self.btn_roi1.setObjectName("btn_roi1")
        self.btn_roi2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_roi2.setGeometry(QtCore.QRect(10, 390, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_roi2.setFont(font)
        self.btn_roi2.setStyleSheet("QPushButton {\n"
"    background-color: #FFB62D;\n"
"    border-radius: 10px;\n"
"    border: 1px solid black;\n"
"}\n"
" \n"
"QPushButton:hover {\n"
"    background-color: #FFA500;\n"
"}\n"
" \n"
"QPushButton:pressed {\n"
"    background-color: #FFB62D;\n"
"    padding-left: 1px;\n"
"    padding-top: 1px;\n"
"}")
        self.btn_roi2.setObjectName("btn_roi2")
        self.btn_iq = QtWidgets.QPushButton(self.centralwidget)
        self.btn_iq.setGeometry(QtCore.QRect(10, 430, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_iq.setFont(font)
        self.btn_iq.setStyleSheet("QPushButton {\n"
"    background-color: #FFB62D;\n"
"    border-radius: 10px;\n"
"    border: 1px solid black;\n"
"}\n"
" \n"
"QPushButton:hover {\n"
"    background-color: #FFA500;\n"
"}\n"
" \n"
"QPushButton:pressed {\n"
"    background-color: #FFB62D;\n"
"    padding-left: 1px;\n"
"    padding-top: 1px;\n"
"}")
        self.btn_iq.setObjectName("btn_iq")
        self.slider_kernel_gaussian = QtWidgets.QSlider(self.centralwidget)
        self.slider_kernel_gaussian.setGeometry(QtCore.QRect(10, 530, 211, 22))
        self.slider_kernel_gaussian.setStyleSheet("QSlider::handle:horizontal {\n"
"    background-color: #FFB62D;\n"
"\n"
"}")
        self.slider_kernel_gaussian.setOrientation(QtCore.Qt.Horizontal)
        self.slider_kernel_gaussian.setInvertedAppearance(False)
        self.slider_kernel_gaussian.setObjectName("slider_kernel_gaussian")
        self.slider_sharp_name = QtWidgets.QLabel(self.centralwidget)
        self.slider_sharp_name.setGeometry(QtCore.QRect(10, 570, 131, 21))
        self.slider_sharp_name.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.slider_sharp_name.setFont(font)
        self.slider_sharp_name.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.slider_sharp_name.setStyleSheet("font: 75 12pt \"Segoe UI\";\n"
"")
        self.slider_sharp_name.setAlignment(QtCore.Qt.AlignCenter)
        self.slider_sharp_name.setWordWrap(False)
        self.slider_sharp_name.setObjectName("slider_sharp_name")
        self.slider_kernel_sharp = QtWidgets.QSlider(self.centralwidget)
        self.slider_kernel_sharp.setGeometry(QtCore.QRect(10, 600, 211, 22))
        self.slider_kernel_sharp.setStyleSheet("QSlider::handle:horizontal {\n"
"    background-color: #FFB62D;\n"
"\n"
"}")
        self.slider_kernel_sharp.setOrientation(QtCore.Qt.Horizontal)
        self.slider_kernel_sharp.setInvertedAppearance(False)
        self.slider_kernel_sharp.setObjectName("slider_kernel_sharp")
        self.radio_axial = QtWidgets.QRadioButton(self.centralwidget)
        self.radio_axial.setGeometry(QtCore.QRect(280, 60, 95, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.radio_axial.setFont(font)
        self.radio_axial.setObjectName("radio_axial")
        self.label_dim_x = QtWidgets.QLabel(self.centralwidget)
        self.label_dim_x.setGeometry(QtCore.QRect(10, 740, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_dim_x.setFont(font)
        self.label_dim_x.setObjectName("label_dim_x")
        self.line_dim_x = QtWidgets.QLineEdit(self.centralwidget)
        self.line_dim_x.setGeometry(QtCore.QRect(120, 741, 101, 31))
        self.line_dim_x.setObjectName("line_dim_x")
        self.label_dim_y = QtWidgets.QLabel(self.centralwidget)
        self.label_dim_y.setGeometry(QtCore.QRect(10, 780, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_dim_y.setFont(font)
        self.label_dim_y.setObjectName("label_dim_y")
        self.line_dim_y = QtWidgets.QLineEdit(self.centralwidget)
        self.line_dim_y.setGeometry(QtCore.QRect(120, 781, 101, 31))
        self.line_dim_y.setObjectName("line_dim_y")
        self.line_pixel = QtWidgets.QLineEdit(self.centralwidget)
        self.line_pixel.setGeometry(QtCore.QRect(120, 821, 101, 31))
        self.line_pixel.setObjectName("line_pixel")
        self.label_pixel = QtWidgets.QLabel(self.centralwidget)
        self.label_pixel.setGeometry(QtCore.QRect(10, 820, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_pixel.setFont(font)
        self.label_pixel.setObjectName("label_pixel")
        self.line_slices = QtWidgets.QLineEdit(self.centralwidget)
        self.line_slices.setGeometry(QtCore.QRect(120, 861, 101, 31))
        self.line_slices.setObjectName("line_slices")
        self.label_slices = QtWidgets.QLabel(self.centralwidget)
        self.label_slices.setGeometry(QtCore.QRect(10, 860, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_slices.setFont(font)
        self.label_slices.setObjectName("label_slices")
        self.btn_rec_cpu = QtWidgets.QPushButton(self.centralwidget)
        self.btn_rec_cpu.setGeometry(QtCore.QRect(10, 910, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_rec_cpu.setFont(font)
        self.btn_rec_cpu.setStyleSheet("QPushButton {\n"
"    background-color: #FFB62D;\n"
"    border-radius: 10px;\n"
"    border: 1px solid black;\n"
"}\n"
" \n"
"QPushButton:hover {\n"
"    background-color: #FFA500;\n"
"}\n"
" \n"
"QPushButton:pressed {\n"
"    background-color: #FFB62D;\n"
"    padding-left: 1px;\n"
"    padding-top: 1px;\n"
"}")
        self.btn_rec_cpu.setObjectName("btn_rec_cpu")
        self.btn_rec_gpu = QtWidgets.QPushButton(self.centralwidget)
        self.btn_rec_gpu.setGeometry(QtCore.QRect(10, 950, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_rec_gpu.setFont(font)
        self.btn_rec_gpu.setStyleSheet("QPushButton {\n"
"    background-color: #FFB62D;\n"
"    border-radius: 10px;\n"
"    border: 1px solid black;\n"
"}\n"
" \n"
"QPushButton:hover {\n"
"    background-color: #FFA500;\n"
"}\n"
" \n"
"QPushButton:pressed {\n"
"    background-color: #FFB62D;\n"
"    padding-left: 1px;\n"
"    padding-top: 1px;\n"
"}")
        self.btn_rec_gpu.setObjectName("btn_rec_gpu")
        self.radio_coronal = QtWidgets.QRadioButton(self.centralwidget)
        self.radio_coronal.setGeometry(QtCore.QRect(380, 60, 95, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.radio_coronal.setFont(font)
        self.radio_coronal.setObjectName("radio_coronal")
        self.radio_sagital = QtWidgets.QRadioButton(self.centralwidget)
        self.radio_sagital.setGeometry(QtCore.QRect(490, 60, 95, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.radio_sagital.setFont(font)
        self.radio_sagital.setObjectName("radio_sagital")
        self.label_min = QtWidgets.QLabel(self.centralwidget)
        self.label_min.setGeometry(QtCore.QRect(640, 70, 31, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_min.setFont(font)
        self.label_min.setObjectName("label_min")
        self.label_max = QtWidgets.QLabel(self.centralwidget)
        self.label_max.setGeometry(QtCore.QRect(750, 70, 31, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_max.setFont(font)
        self.label_max.setObjectName("label_max")
        self.label_mean = QtWidgets.QLabel(self.centralwidget)
        self.label_mean.setGeometry(QtCore.QRect(1010, 70, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_mean.setFont(font)
        self.label_mean.setObjectName("label_mean")
        self.label_std = QtWidgets.QLabel(self.centralwidget)
        self.label_std.setGeometry(QtCore.QRect(880, 70, 31, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_std.setFont(font)
        self.label_std.setObjectName("label_std")
        self.label_sum = QtWidgets.QLabel(self.centralwidget)
        self.label_sum.setGeometry(QtCore.QRect(1140, 70, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_sum.setFont(font)
        self.label_sum.setObjectName("label_sum")
        self.label_value = QtWidgets.QLabel(self.centralwidget)
        self.label_value.setGeometry(QtCore.QRect(730, 950, 211, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_value.setFont(font)
        self.label_value.setObjectName("label_value")
        self.label_mAs = QtWidgets.QLabel(self.centralwidget)
        self.label_mAs.setGeometry(QtCore.QRect(420, 950, 151, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_mAs.setFont(font)
        self.label_mAs.setObjectName("label_mAs")
        self.label_kV = QtWidgets.QLabel(self.centralwidget)
        self.label_kV.setGeometry(QtCore.QRect(280, 950, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_kV.setFont(font)
        self.label_kV.setObjectName("label_kV")
        self.label_foco = QtWidgets.QLabel(self.centralwidget)
        self.label_foco.setGeometry(QtCore.QRect(540, 950, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_foco.setFont(font)
        self.label_foco.setObjectName("label_foco")
        self.label_Z = QtWidgets.QLabel(self.centralwidget)
        self.label_Z.setGeometry(QtCore.QRect(640, 950, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_Z.setFont(font)
        self.label_Z.setObjectName("label_Z")
        self.exp = QtWidgets.QGraphicsView(self.centralwidget)
        self.exp.setGeometry(QtCore.QRect(280, 90, 981, 851))
        self.exp.setObjectName("exp")
        self.discr_colormaps = QtWidgets.QPushButton(self.centralwidget)
        self.discr_colormaps.setGeometry(QtCore.QRect(230, 160, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.discr_colormaps.setFont(font)
        self.discr_colormaps.setStyleSheet("QPushButton {\n"
"    border: none; /* Remove a borda */\n"
"    background-color: transparent; /* Fundo transparente */\n"
"    color: blue; /* Cor do texto em azul */\n"
"}\n"
"")
        self.discr_colormaps.setObjectName("discr_colormaps")
        self.discr_rotate = QtWidgets.QPushButton(self.centralwidget)
        self.discr_rotate.setGeometry(QtCore.QRect(230, 200, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.discr_rotate.setFont(font)
        self.discr_rotate.setStyleSheet("QPushButton {\n"
"    border: none; /* Remove a borda */\n"
"    background-color: transparent; /* Fundo transparente */\n"
"    color: blue; /* Cor do texto em azul */\n"
"}\n"
"")
        self.discr_rotate.setObjectName("discr_rotate")
        self.discr_histagram = QtWidgets.QPushButton(self.centralwidget)
        self.discr_histagram.setGeometry(QtCore.QRect(230, 240, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.discr_histagram.setFont(font)
        self.discr_histagram.setStyleSheet("QPushButton {\n"
"    border: none; /* Remove a borda */\n"
"    background-color: transparent; /* Fundo transparente */\n"
"    color: blue; /* Cor do texto em azul */\n"
"}\n"
"")
        self.discr_histagram.setObjectName("discr_histagram")
        self.discr_flatfield = QtWidgets.QPushButton(self.centralwidget)
        self.discr_flatfield.setGeometry(QtCore.QRect(230, 280, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.discr_flatfield.setFont(font)
        self.discr_flatfield.setStyleSheet("QPushButton {\n"
"    border: none; /* Remove a borda */\n"
"    background-color: transparent; /* Fundo transparente */\n"
"    color: blue; /* Cor do texto em azul */\n"
"}\n"
"")
        self.discr_flatfield.setObjectName("discr_flatfield")
        self.discr_roi1 = QtWidgets.QPushButton(self.centralwidget)
        self.discr_roi1.setGeometry(QtCore.QRect(230, 350, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.discr_roi1.setFont(font)
        self.discr_roi1.setStyleSheet("QPushButton {\n"
"    border: none; /* Remove a borda */\n"
"    background-color: transparent; /* Fundo transparente */\n"
"    color: blue; /* Cor do texto em azul */\n"
"}\n"
"")
        self.discr_roi1.setObjectName("discr_roi1")
        self.discr_roi2 = QtWidgets.QPushButton(self.centralwidget)
        self.discr_roi2.setGeometry(QtCore.QRect(230, 390, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.discr_roi2.setFont(font)
        self.discr_roi2.setStyleSheet("QPushButton {\n"
"    border: none; /* Remove a borda */\n"
"    background-color: transparent; /* Fundo transparente */\n"
"    color: blue; /* Cor do texto em azul */\n"
"}\n"
"")
        self.discr_roi2.setObjectName("discr_roi2")
        self.discr_cnr_snr = QtWidgets.QPushButton(self.centralwidget)
        self.discr_cnr_snr.setGeometry(QtCore.QRect(230, 430, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.discr_cnr_snr.setFont(font)
        self.discr_cnr_snr.setStyleSheet("QPushButton {\n"
"    border: none; /* Remove a borda */\n"
"    background-color: transparent; /* Fundo transparente */\n"
"    color: blue; /* Cor do texto em azul */\n"
"}\n"
"")
        self.discr_cnr_snr.setObjectName("discr_cnr_snr")
        self.discr_cnoise = QtWidgets.QPushButton(self.centralwidget)
        self.discr_cnoise.setGeometry(QtCore.QRect(230, 520, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.discr_cnoise.setFont(font)
        self.discr_cnoise.setStyleSheet("QPushButton {\n"
"    border: none; /* Remove a borda */\n"
"    background-color: transparent; /* Fundo transparente */\n"
"    color: blue; /* Cor do texto em azul */\n"
"}\n"
"")
        self.discr_cnoise.setObjectName("discr_cnoise")
        self.discr_sharpness = QtWidgets.QPushButton(self.centralwidget)
        self.discr_sharpness.setGeometry(QtCore.QRect(230, 590, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.discr_sharpness.setFont(font)
        self.discr_sharpness.setStyleSheet("QPushButton {\n"
"    border: none; /* Remove a borda */\n"
"    background-color: transparent; /* Fundo transparente */\n"
"    color: blue; /* Cor do texto em azul */\n"
"}\n"
"")
        self.discr_sharpness.setObjectName("discr_sharpness")
        self.discr_image_id = QtWidgets.QPushButton(self.centralwidget)
        self.discr_image_id.setGeometry(QtCore.QRect(230, 670, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.discr_image_id.setFont(font)
        self.discr_image_id.setStyleSheet("QPushButton {\n"
"    border: none; /* Remove a borda */\n"
"    background-color: transparent; /* Fundo transparente */\n"
"    color: blue; /* Cor do texto em azul */\n"
"}\n"
"")
        self.discr_image_id.setObjectName("discr_image_id")
        self.discr_proj = QtWidgets.QPushButton(self.centralwidget)
        self.discr_proj.setGeometry(QtCore.QRect(230, 700, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.discr_proj.setFont(font)
        self.discr_proj.setStyleSheet("QPushButton {\n"
"    border: none; /* Remove a borda */\n"
"    background-color: transparent; /* Fundo transparente */\n"
"    color: blue; /* Cor do texto em azul */\n"
"}\n"
"")
        self.discr_proj.setObjectName("discr_proj")
        self.discr_dimx = QtWidgets.QPushButton(self.centralwidget)
        self.discr_dimx.setGeometry(QtCore.QRect(230, 740, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.discr_dimx.setFont(font)
        self.discr_dimx.setStyleSheet("QPushButton {\n"
"    border: none; /* Remove a borda */\n"
"    background-color: transparent; /* Fundo transparente */\n"
"    color: blue; /* Cor do texto em azul */\n"
"}\n"
"")
        self.discr_dimx.setObjectName("discr_dimx")
        self.discr_dimy = QtWidgets.QPushButton(self.centralwidget)
        self.discr_dimy.setGeometry(QtCore.QRect(230, 780, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.discr_dimy.setFont(font)
        self.discr_dimy.setStyleSheet("QPushButton {\n"
"    border: none; /* Remove a borda */\n"
"    background-color: transparent; /* Fundo transparente */\n"
"    color: blue; /* Cor do texto em azul */\n"
"}\n"
"")
        self.discr_dimy.setObjectName("discr_dimy")
        self.discr_pixelsize = QtWidgets.QPushButton(self.centralwidget)
        self.discr_pixelsize.setGeometry(QtCore.QRect(230, 820, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.discr_pixelsize.setFont(font)
        self.discr_pixelsize.setStyleSheet("QPushButton {\n"
"    border: none; /* Remove a borda */\n"
"    background-color: transparent; /* Fundo transparente */\n"
"    color: blue; /* Cor do texto em azul */\n"
"}\n"
"")
        self.discr_pixelsize.setObjectName("discr_pixelsize")
        self.discr_slices = QtWidgets.QPushButton(self.centralwidget)
        self.discr_slices.setGeometry(QtCore.QRect(230, 860, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.discr_slices.setFont(font)
        self.discr_slices.setStyleSheet("QPushButton {\n"
"    border: none; /* Remove a borda */\n"
"    background-color: transparent; /* Fundo transparente */\n"
"    color: blue; /* Cor do texto em azul */\n"
"}\n"
"")
        self.discr_slices.setObjectName("discr_slices")
        self.discr_recon_cpu = QtWidgets.QPushButton(self.centralwidget)
        self.discr_recon_cpu.setGeometry(QtCore.QRect(230, 910, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.discr_recon_cpu.setFont(font)
        self.discr_recon_cpu.setStyleSheet("QPushButton {\n"
"    border: none; /* Remove a borda */\n"
"    background-color: transparent; /* Fundo transparente */\n"
"    color: blue; /* Cor do texto em azul */\n"
"}\n"
"")
        self.discr_recon_cpu.setObjectName("discr_recon_cpu")
        self.discr_recon_gpu = QtWidgets.QPushButton(self.centralwidget)
        self.discr_recon_gpu.setGeometry(QtCore.QRect(230, 950, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.discr_recon_gpu.setFont(font)
        self.discr_recon_gpu.setStyleSheet("QPushButton {\n"
"    border: none; /* Remove a borda */\n"
"    background-color: transparent; /* Fundo transparente */\n"
"    color: blue; /* Cor do texto em azul */\n"
"}\n"
"")
        self.discr_recon_gpu.setObjectName("discr_recon_gpu")
        self.discr_axial = QtWidgets.QPushButton(self.centralwidget)
        self.discr_axial.setGeometry(QtCore.QRect(340, 60, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.discr_axial.setFont(font)
        self.discr_axial.setStyleSheet("QPushButton {\n"
"    border: none; /* Remove a borda */\n"
"    background-color: transparent; /* Fundo transparente */\n"
"    color: blue; /* Cor do texto em azul */\n"
"}\n"
"")
        self.discr_axial.setObjectName("discr_axial")
        self.discr_coronal = QtWidgets.QPushButton(self.centralwidget)
        self.discr_coronal.setGeometry(QtCore.QRect(460, 60, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.discr_coronal.setFont(font)
        self.discr_coronal.setStyleSheet("QPushButton {\n"
"    border: none; /* Remove a borda */\n"
"    background-color: transparent; /* Fundo transparente */\n"
"    color: blue; /* Cor do texto em azul */\n"
"}\n"
"")
        self.discr_coronal.setObjectName("discr_coronal")
        self.discr_sagital = QtWidgets.QPushButton(self.centralwidget)
        self.discr_sagital.setGeometry(QtCore.QRect(560, 60, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.discr_sagital.setFont(font)
        self.discr_sagital.setStyleSheet("QPushButton {\n"
"    border: none; /* Remove a borda */\n"
"    background-color: transparent; /* Fundo transparente */\n"
"    color: blue; /* Cor do texto em azul */\n"
"}\n"
"")
        self.discr_sagital.setObjectName("discr_sagital")
        self.line_image_id = QtWidgets.QLineEdit(self.centralwidget)
        self.line_image_id.setGeometry(QtCore.QRect(120, 661, 101, 31))
        self.line_image_id.setObjectName("line_image_id")
        self.label_image_id = QtWidgets.QLabel(self.centralwidget)
        self.label_image_id.setGeometry(QtCore.QRect(10, 660, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_image_id.setFont(font)
        self.label_image_id.setObjectName("label_image_id")
        self.line_proj = QtWidgets.QLineEdit(self.centralwidget)
        self.line_proj.setGeometry(QtCore.QRect(120, 701, 101, 31))
        self.line_proj.setObjectName("line_proj")
        self.label_proj = QtWidgets.QLabel(self.centralwidget)
        self.label_proj.setGeometry(QtCore.QRect(10, 700, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_proj.setFont(font)
        self.label_proj.setObjectName("label_proj")
        self.btn_save_image = QtWidgets.QPushButton(self.centralwidget)
        self.btn_save_image.setGeometry(QtCore.QRect(1090, 950, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_save_image.setFont(font)
        self.btn_save_image.setStyleSheet("QPushButton {\n"
"    background-color: #FFB62D;\n"
"    border-radius: 10px;\n"
"    border: 1px solid black;\n"
"}\n"
" \n"
"QPushButton:hover {\n"
"    background-color: #FFA500;\n"
"}\n"
" \n"
"QPushButton:pressed {\n"
"    background-color: #FFB62D;\n"
"    padding-left: 1px;\n"
"    padding-top: 1px;\n"
"}")
        self.btn_save_image.setObjectName("btn_save_image")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 0, 121, 51))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 630, 151, 31))
        self.label_2.setStyleSheet("font: 87 16pt \"Segoe UI\";\n"
"font-weight: Bold")
        self.label_2.setObjectName("label_2")
        self.slider_sharp_name_2 = QtWidgets.QLabel(self.centralwidget)
        self.slider_sharp_name_2.setGeometry(QtCore.QRect(10, 500, 91, 21))
        self.slider_sharp_name_2.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.slider_sharp_name_2.setFont(font)
        self.slider_sharp_name_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.slider_sharp_name_2.setStyleSheet("font: 75 12pt \"Segoe UI\";\n"
"")
        self.slider_sharp_name_2.setAlignment(QtCore.Qt.AlignCenter)
        self.slider_sharp_name_2.setWordWrap(False)
        self.slider_sharp_name_2.setObjectName("slider_sharp_name_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 470, 151, 31))
        self.label_3.setStyleSheet("font: 87 16pt \"Segoe UI\";\n"
"font-weight: Bold")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 320, 151, 31))
        self.label_4.setStyleSheet("font: 87 16pt \"Segoe UI\";\n"
"font-weight: Bold")
        self.label_4.setObjectName("label_4")
        self.discr_colormaps_2 = QtWidgets.QPushButton(self.centralwidget)
        self.discr_colormaps_2.setGeometry(QtCore.QRect(230, 80, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.discr_colormaps_2.setFont(font)
        self.discr_colormaps_2.setStyleSheet("QPushButton {\n"
"    border: none; /* Remove a borda */\n"
"    background-color: transparent; /* Fundo transparente */\n"
"    color: blue; /* Cor do texto em azul */\n"
"}\n"
"")
        self.discr_colormaps_2.setObjectName("discr_colormaps_2")
        self.discr_colormaps_3 = QtWidgets.QPushButton(self.centralwidget)
        self.discr_colormaps_3.setGeometry(QtCore.QRect(230, 120, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.discr_colormaps_3.setFont(font)
        self.discr_colormaps_3.setStyleSheet("QPushButton {\n"
"    border: none; /* Remove a borda */\n"
"    background-color: transparent; /* Fundo transparente */\n"
"    color: blue; /* Cor do texto em azul */\n"
"}\n"
"")
        self.discr_colormaps_3.setObjectName("discr_colormaps_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 50, 151, 31))
        self.label_5.setStyleSheet("font: 87 16pt \"Segoe UI\";\n"
"font-weight: Bold")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(280, 0, 191, 31))
        self.label_6.setStyleSheet("font: 87 16pt \"Segoe UI\";\n"
"font-weight: Bold")
        self.label_6.setObjectName("label_6")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CT Industrial Visualizer"))
        self.btn_open.setText(_translate("MainWindow", "Open"))
        self.btn_colormap.setText(_translate("MainWindow", "Colormaps"))
        self.btn_clear.setText(_translate("MainWindow", "Clear"))
        self.btn_rot.setText(_translate("MainWindow", "Rotate"))
        self.btn_hist.setText(_translate("MainWindow", "Histogram"))
        self.btn_flat.setText(_translate("MainWindow", "Apply Flat Field"))
        self.btn_roi1.setText(_translate("MainWindow", "ROI 1"))
        self.btn_roi2.setText(_translate("MainWindow", "ROI 2"))
        self.btn_iq.setText(_translate("MainWindow", "Calculate CNR - SNR"))
        self.slider_sharp_name.setText(_translate("MainWindow", "Improve Sharpness"))
        self.radio_axial.setText(_translate("MainWindow", "Axial"))
        self.label_dim_x.setText(_translate("MainWindow", "Dim X:"))
        self.label_dim_y.setText(_translate("MainWindow", "Dim Y:"))
        self.label_pixel.setText(_translate("MainWindow", "Pixel size (mm):"))
        self.label_slices.setText(_translate("MainWindow", "#Slices:"))
        self.btn_rec_cpu.setText(_translate("MainWindow", "Reconstruction via CPU"))
        self.btn_rec_gpu.setText(_translate("MainWindow", "Reconstruction via GPU"))
        self.radio_coronal.setText(_translate("MainWindow", "Coronal"))
        self.radio_sagital.setText(_translate("MainWindow", "Sagital"))
        self.label_min.setText(_translate("MainWindow", "Min:"))
        self.label_max.setText(_translate("MainWindow", "Max:"))
        self.label_mean.setText(_translate("MainWindow", "Mean:"))
        self.label_std.setText(_translate("MainWindow", "STD:"))
        self.label_sum.setText(_translate("MainWindow", "Sum:"))
        self.label_value.setText(_translate("MainWindow", "Pixel Value: "))
        self.label_mAs.setText(_translate("MainWindow", "mAs:"))
        self.label_kV.setText(_translate("MainWindow", "KV:"))
        self.label_foco.setText(_translate("MainWindow", "Foco:"))
        self.label_Z.setText(_translate("MainWindow", "Z:"))
        self.discr_colormaps.setText(_translate("MainWindow", "?"))
        self.discr_rotate.setText(_translate("MainWindow", "?"))
        self.discr_histagram.setText(_translate("MainWindow", "?"))
        self.discr_flatfield.setText(_translate("MainWindow", "?"))
        self.discr_roi1.setText(_translate("MainWindow", "?"))
        self.discr_roi2.setText(_translate("MainWindow", "?"))
        self.discr_cnr_snr.setText(_translate("MainWindow", "?"))
        self.discr_cnoise.setText(_translate("MainWindow", "?"))
        self.discr_sharpness.setText(_translate("MainWindow", "?"))
        self.discr_image_id.setText(_translate("MainWindow", "?"))
        self.discr_proj.setText(_translate("MainWindow", "?"))
        self.discr_dimx.setText(_translate("MainWindow", "?"))
        self.discr_dimy.setText(_translate("MainWindow", "?"))
        self.discr_pixelsize.setText(_translate("MainWindow", "?"))
        self.discr_slices.setText(_translate("MainWindow", "?"))
        self.discr_recon_cpu.setText(_translate("MainWindow", "?"))
        self.discr_recon_gpu.setText(_translate("MainWindow", "?"))
        self.discr_axial.setText(_translate("MainWindow", "?"))
        self.discr_coronal.setText(_translate("MainWindow", "?"))
        self.discr_sagital.setText(_translate("MainWindow", "?"))
        self.label_image_id.setText(_translate("MainWindow", "Image:"))
        self.label_proj.setText(_translate("MainWindow", "Projections:"))
        self.btn_save_image.setText(_translate("MainWindow", "Save Image"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><img src=\":/Logo/QT designer assets/logo-ibti SVG.png\"/></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "Reconstruction"))
        self.slider_sharp_name_2.setText(_translate("MainWindow", "Reduce noise"))
        self.label_3.setText(_translate("MainWindow", "Filters"))
        self.label_4.setText(_translate("MainWindow", "Image quality"))
        self.discr_colormaps_2.setText(_translate("MainWindow", "?"))
        self.discr_colormaps_3.setText(_translate("MainWindow", "?"))
        self.label_5.setText(_translate("MainWindow", "Controls"))
        self.label_6.setText(_translate("MainWindow", "Tomographic views"))
import QT designer assets__rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
