# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ct_visualizer2.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1307, 1087)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 31))
        self.scrollArea.setStyleSheet("QScrollArea {\n"
"    border: none;\n"
"}\n"
"")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1289, 1028))
        self.scrollAreaWidgetContents.setStyleSheet("")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btn_save_image = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btn_save_image.setMinimumSize(QtCore.QSize(200, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_save_image.setFont(font)
        self.btn_save_image.setStyleSheet("QPushButton {\n"
"    background-color: #FFB62D;\n"
"    border-radius: 10px;\n"
"    border: 1px solid black;\n"
"}\n"
" \n"
"QPushButton:hover {\n"
"    background-color: #FFA500;\n"
"}\n"
" \n"
"QPushButton:pressed {\n"
"    background-color: #FFB62D;\n"
"    padding-left: 1px;\n"
"    padding-top: 1px;\n"
"}")
        self.btn_save_image.setObjectName("btn_save_image")
        self.gridLayout_2.addWidget(self.btn_save_image, 28, 18, 1, 2)
        self.btn_rot = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btn_rot.setMinimumSize(QtCore.QSize(0, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_rot.setFont(font)
        self.btn_rot.setStyleSheet("QPushButton {\n"
"    background-color: #FFB62D;\n"
"    border-radius: 10px;\n"
"    border: 1px solid black;\n"
"}\n"
" \n"
"QPushButton:hover {\n"
"    background-color: #FFA500;\n"
"}\n"
" \n"
"QPushButton:pressed {\n"
"    background-color: #FFB62D;\n"
"    padding-left: 1px;\n"
"    padding-top: 1px;\n"
"}")
        self.btn_rot.setObjectName("btn_rot")
        self.gridLayout_2.addWidget(self.btn_rot, 6, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_6.setStyleSheet("font: 87 16pt \"Segoe UI\";\n"
"font-weight: Bold")
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 0, 3, 1, 8)
        self.exp = QtWidgets.QGraphicsView(self.scrollAreaWidgetContents)
        self.exp.setMinimumSize(QtCore.QSize(0, 23))
        self.exp.setObjectName("exp")
        self.gridLayout_2.addWidget(self.exp, 3, 3, 25, 17)
        self.btn_colormap = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btn_colormap.setMinimumSize(QtCore.QSize(0, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_colormap.setFont(font)
        self.btn_colormap.setStyleSheet("QPushButton {\n"
"    background-color: #FFB62D;\n"
"    border-radius: 10px;\n"
"    border: 1px solid black;\n"
"}\n"
" \n"
"QPushButton:hover {\n"
"    background-color: #FFA500;\n"
"}\n"
" \n"
"QPushButton:pressed {\n"
"    background-color: #FFB62D;\n"
"    padding-left: 1px;\n"
"    padding-top: 1px;\n"
"}")
        self.btn_colormap.setObjectName("btn_colormap")
        self.gridLayout_2.addWidget(self.btn_colormap, 4, 0, 1, 1)
        self.btn_clear = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btn_clear.setMinimumSize(QtCore.QSize(0, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_clear.setFont(font)
        self.btn_clear.setStyleSheet("QPushButton {\n"
"    background-color: #FFB62D;\n"
"    border-radius: 10px;\n"
"    border: 1px solid black;\n"
"}\n"
" \n"
"QPushButton:hover {\n"
"    background-color: #FFA500;\n"
"}\n"
" \n"
"QPushButton:pressed {\n"
"    background-color: #FFB62D;\n"
"    padding-left: 1px;\n"
"    padding-top: 1px;\n"
"}")
        self.btn_clear.setObjectName("btn_clear")
        self.gridLayout_2.addWidget(self.btn_clear, 5, 0, 1, 1)
        self.btn_roi2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btn_roi2.setMinimumSize(QtCore.QSize(0, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_roi2.setFont(font)
        self.btn_roi2.setStyleSheet("QPushButton {\n"
"    background-color: #FFB62D;\n"
"    border-radius: 10px;\n"
"    border: 1px solid black;\n"
"}\n"
" \n"
"QPushButton:hover {\n"
"    background-color: #FFA500;\n"
"}\n"
" \n"
"QPushButton:pressed {\n"
"    background-color: #FFB62D;\n"
"    padding-left: 1px;\n"
"    padding-top: 1px;\n"
"}")
        self.btn_roi2.setObjectName("btn_roi2")
        self.gridLayout_2.addWidget(self.btn_roi2, 11, 0, 1, 1)
        self.btn_hist = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btn_hist.setMinimumSize(QtCore.QSize(0, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_hist.setFont(font)
        self.btn_hist.setStyleSheet("QPushButton {\n"
"    background-color: #FFB62D;\n"
"    border-radius: 10px;\n"
"    border: 1px solid black;\n"
"}\n"
" \n"
"QPushButton:hover {\n"
"    background-color: #FFA500;\n"
"}\n"
" \n"
"QPushButton:pressed {\n"
"    background-color: #FFB62D;\n"
"    padding-left: 1px;\n"
"    padding-top: 1px;\n"
"}")
        self.btn_hist.setObjectName("btn_hist")
        self.gridLayout_2.addWidget(self.btn_hist, 7, 0, 1, 1)
        self.btn_roi1 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btn_roi1.setMinimumSize(QtCore.QSize(0, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_roi1.setFont(font)
        self.btn_roi1.setStyleSheet("QPushButton {\n"
"    background-color: #FFB62D;\n"
"    border-radius: 10px;\n"
"    border: 1px solid black;\n"
"}\n"
" \n"
"QPushButton:hover {\n"
"    background-color: #FFA500;\n"
"}\n"
" \n"
"QPushButton:pressed {\n"
"    background-color: #FFB62D;\n"
"    padding-left: 1px;\n"
"    padding-top: 1px;\n"
"}")
        self.btn_roi1.setObjectName("btn_roi1")
        self.gridLayout_2.addWidget(self.btn_roi1, 10, 0, 1, 1)
        self.slider_kernel_gaussian = QtWidgets.QSlider(self.scrollAreaWidgetContents)
        self.slider_kernel_gaussian.setMaximumSize(QtCore.QSize(200, 16777215))
        self.slider_kernel_gaussian.setStyleSheet("QSlider::handle:horizontal {\n"
"    background-color: #FFB62D;\n"
"\n"
"}")
        self.slider_kernel_gaussian.setOrientation(QtCore.Qt.Horizontal)
        self.slider_kernel_gaussian.setInvertedAppearance(False)
        self.slider_kernel_gaussian.setObjectName("slider_kernel_gaussian")
        self.gridLayout_2.addWidget(self.slider_kernel_gaussian, 15, 0, 1, 1)
        self.slider_sharp_name = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.slider_sharp_name.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.slider_sharp_name.setFont(font)
        self.slider_sharp_name.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.slider_sharp_name.setStyleSheet("font: 75 12pt \"Segoe UI\";\n"
"")
        self.slider_sharp_name.setAlignment(QtCore.Qt.AlignCenter)
        self.slider_sharp_name.setWordWrap(False)
        self.slider_sharp_name.setObjectName("slider_sharp_name")
        self.gridLayout_2.addWidget(self.slider_sharp_name, 16, 0, 1, 1)
        self.slider_kernel_sharp = QtWidgets.QSlider(self.scrollAreaWidgetContents)
        self.slider_kernel_sharp.setMaximumSize(QtCore.QSize(200, 16777215))
        self.slider_kernel_sharp.setStyleSheet("QSlider::handle:horizontal {\n"
"    background-color: #FFB62D;\n"
"\n"
"}")
        self.slider_kernel_sharp.setOrientation(QtCore.Qt.Horizontal)
        self.slider_kernel_sharp.setInvertedAppearance(False)
        self.slider_kernel_sharp.setObjectName("slider_kernel_sharp")
        self.gridLayout_2.addWidget(self.slider_kernel_sharp, 17, 0, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_2.setStyleSheet("font: 87 16pt \"Segoe UI\";\n"
"font-weight: Bold")
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 18, 0, 1, 1)
        self.btn_iq = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btn_iq.setMinimumSize(QtCore.QSize(0, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_iq.setFont(font)
        self.btn_iq.setStyleSheet("QPushButton {\n"
"    background-color: #FFB62D;\n"
"    border-radius: 10px;\n"
"    border: 1px solid black;\n"
"}\n"
" \n"
"QPushButton:hover {\n"
"    background-color: #FFA500;\n"
"}\n"
" \n"
"QPushButton:pressed {\n"
"    background-color: #FFB62D;\n"
"    padding-left: 1px;\n"
"    padding-top: 1px;\n"
"}")
        self.btn_iq.setObjectName("btn_iq")
        self.gridLayout_2.addWidget(self.btn_iq, 12, 0, 1, 1)
        self.btn_flat = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btn_flat.setMinimumSize(QtCore.QSize(0, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_flat.setFont(font)
        self.btn_flat.setStyleSheet("QPushButton {\n"
"    background-color: #FFB62D;\n"
"    border-radius: 10px;\n"
"    border: 1px solid black;\n"
"}\n"
" \n"
"QPushButton:hover {\n"
"    background-color: #FFA500;\n"
"}\n"
" \n"
"QPushButton:pressed {\n"
"    background-color: #FFB62D;\n"
"    padding-left: 1px;\n"
"    padding-top: 1px;\n"
"}")
        self.btn_flat.setObjectName("btn_flat")
        self.gridLayout_2.addWidget(self.btn_flat, 8, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_4.setStyleSheet("font: 87 16pt \"Segoe UI\";\n"
"font-weight: Bold")
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 9, 0, 1, 2)
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_3.setStyleSheet("font: 87 16pt \"Segoe UI\";\n"
"font-weight: Bold")
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 13, 0, 1, 1)
        self.slider_sharp_name_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.slider_sharp_name_2.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.slider_sharp_name_2.setFont(font)
        self.slider_sharp_name_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.slider_sharp_name_2.setStyleSheet("font: 75 12pt \"Segoe UI\";\n"
"")
        self.slider_sharp_name_2.setAlignment(QtCore.Qt.AlignCenter)
        self.slider_sharp_name_2.setWordWrap(False)
        self.slider_sharp_name_2.setObjectName("slider_sharp_name_2")
        self.gridLayout_2.addWidget(self.slider_sharp_name_2, 14, 0, 1, 1)
        self.btn_rec_cpu = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btn_rec_cpu.setMinimumSize(QtCore.QSize(0, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_rec_cpu.setFont(font)
        self.btn_rec_cpu.setStyleSheet("QPushButton {\n"
"    background-color: #FFB62D;\n"
"    border-radius: 10px;\n"
"    border: 1px solid black;\n"
"}\n"
" \n"
"QPushButton:hover {\n"
"    background-color: #FFA500;\n"
"}\n"
" \n"
"QPushButton:pressed {\n"
"    background-color: #FFB62D;\n"
"    padding-left: 1px;\n"
"    padding-top: 1px;\n"
"}")
        self.btn_rec_cpu.setObjectName("btn_rec_cpu")
        self.gridLayout_2.addWidget(self.btn_rec_cpu, 27, 0, 1, 1)
        self.btn_rec_gpu = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btn_rec_gpu.setMinimumSize(QtCore.QSize(0, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_rec_gpu.setFont(font)
        self.btn_rec_gpu.setStyleSheet("QPushButton {\n"
"    background-color: #FFB62D;\n"
"    border-radius: 10px;\n"
"    border: 1px solid black;\n"
"}\n"
" \n"
"QPushButton:hover {\n"
"    background-color: #FFA500;\n"
"}\n"
" \n"
"QPushButton:pressed {\n"
"    background-color: #FFB62D;\n"
"    padding-left: 1px;\n"
"    padding-top: 1px;\n"
"}")
        self.btn_rec_gpu.setObjectName("btn_rec_gpu")
        self.gridLayout_2.addWidget(self.btn_rec_gpu, 28, 0, 1, 1)
        self.label_value = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_value.setFont(font)
        self.label_value.setObjectName("label_value")
        self.gridLayout_2.addWidget(self.label_value, 28, 3, 1, 4)
        self.label_foco = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_foco.setFont(font)
        self.label_foco.setObjectName("label_foco")
        self.gridLayout_2.addWidget(self.label_foco, 28, 11, 1, 1)
        self.label_mean = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_mean.setFont(font)
        self.label_mean.setObjectName("label_mean")
        self.gridLayout_2.addWidget(self.label_mean, 2, 18, 1, 1)
        self.label_mAs = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_mAs.setFont(font)
        self.label_mAs.setObjectName("label_mAs")
        self.gridLayout_2.addWidget(self.label_mAs, 28, 7, 1, 1)
        self.label_std = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_std.setFont(font)
        self.label_std.setObjectName("label_std")
        self.gridLayout_2.addWidget(self.label_std, 2, 16, 1, 1)
        self.radio_axial = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.radio_axial.setFont(font)
        self.radio_axial.setObjectName("radio_axial")
        self.gridLayout_2.addWidget(self.radio_axial, 2, 3, 1, 1)
        self.label_sum = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_sum.setFont(font)
        self.label_sum.setObjectName("label_sum")
        self.gridLayout_2.addWidget(self.label_sum, 2, 17, 1, 1)
        self.discr_axial = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.discr_axial.setMaximumSize(QtCore.QSize(30, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.discr_axial.setFont(font)
        self.discr_axial.setStyleSheet("QPushButton {\n"
"    border: none; /* Remove a borda */\n"
"    background-color: transparent; /* Fundo transparente */\n"
"    color: blue; /* Cor do texto em azul */\n"
"}\n"
"")
        self.discr_axial.setObjectName("discr_axial")
        self.gridLayout_2.addWidget(self.discr_axial, 2, 4, 1, 1)
        self.radio_coronal = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.radio_coronal.setFont(font)
        self.radio_coronal.setObjectName("radio_coronal")
        self.gridLayout_2.addWidget(self.radio_coronal, 2, 6, 1, 1)
        self.label_max = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_max.setFont(font)
        self.label_max.setObjectName("label_max")
        self.gridLayout_2.addWidget(self.label_max, 2, 15, 1, 1)
        self.label_min = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_min.setFont(font)
        self.label_min.setObjectName("label_min")
        self.gridLayout_2.addWidget(self.label_min, 2, 14, 1, 1)
        self.discr_cnr_snr = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.discr_cnr_snr.setFont(font)
        self.discr_cnr_snr.setStyleSheet("QPushButton {\n"
"    border: none; /* Remove a borda */\n"
"    background-color: transparent; /* Fundo transparente */\n"
"    color: blue; /* Cor do texto em azul */\n"
"}\n"
"")
        self.discr_cnr_snr.setObjectName("discr_cnr_snr")
        self.gridLayout_2.addWidget(self.discr_cnr_snr, 12, 1, 1, 1)
        self.discr_flatfield = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.discr_flatfield.setFont(font)
        self.discr_flatfield.setStyleSheet("QPushButton {\n"
"    border: none; /* Remove a borda */\n"
"    background-color: transparent; /* Fundo transparente */\n"
"    color: blue; /* Cor do texto em azul */\n"
"}\n"
"")
        self.discr_flatfield.setObjectName("discr_flatfield")
        self.gridLayout_2.addWidget(self.discr_flatfield, 8, 1, 1, 1)
        self.discr_roi2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.discr_roi2.setFont(font)
        self.discr_roi2.setStyleSheet("QPushButton {\n"
"    border: none; /* Remove a borda */\n"
"    background-color: transparent; /* Fundo transparente */\n"
"    color: blue; /* Cor do texto em azul */\n"
"}\n"
"")
        self.discr_roi2.setObjectName("discr_roi2")
        self.gridLayout_2.addWidget(self.discr_roi2, 11, 1, 1, 1)
        self.discr_roi1 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.discr_roi1.setFont(font)
        self.discr_roi1.setStyleSheet("QPushButton {\n"
"    border: none; /* Remove a borda */\n"
"    background-color: transparent; /* Fundo transparente */\n"
"    color: blue; /* Cor do texto em azul */\n"
"}\n"
"")
        self.discr_roi1.setObjectName("discr_roi1")
        self.gridLayout_2.addWidget(self.discr_roi1, 10, 1, 1, 1)
        self.discr_histagram = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.discr_histagram.setFont(font)
        self.discr_histagram.setStyleSheet("QPushButton {\n"
"    border: none; /* Remove a borda */\n"
"    background-color: transparent; /* Fundo transparente */\n"
"    color: blue; /* Cor do texto em azul */\n"
"}\n"
"")
        self.discr_histagram.setObjectName("discr_histagram")
        self.gridLayout_2.addWidget(self.discr_histagram, 7, 1, 1, 1)
        self.discr_colormaps_3 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.discr_colormaps_3.setFont(font)
        self.discr_colormaps_3.setStyleSheet("QPushButton {\n"
"    border: none; /* Remove a borda */\n"
"    background-color: transparent; /* Fundo transparente */\n"
"    color: blue; /* Cor do texto em azul */\n"
"}\n"
"")
        self.discr_colormaps_3.setObjectName("discr_colormaps_3")
        self.gridLayout_2.addWidget(self.discr_colormaps_3, 4, 1, 1, 1)
        self.discr_rotate = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.discr_rotate.setFont(font)
        self.discr_rotate.setStyleSheet("QPushButton {\n"
"    border: none; /* Remove a borda */\n"
"    background-color: transparent; /* Fundo transparente */\n"
"    color: blue; /* Cor do texto em azul */\n"
"}\n"
"")
        self.discr_rotate.setObjectName("discr_rotate")
        self.gridLayout_2.addWidget(self.discr_rotate, 6, 1, 1, 1)
        self.discr_colormaps = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.discr_colormaps.setFont(font)
        self.discr_colormaps.setStyleSheet("QPushButton {\n"
"    border: none; /* Remove a borda */\n"
"    background-color: transparent; /* Fundo transparente */\n"
"    color: blue; /* Cor do texto em azul */\n"
"}\n"
"")
        self.discr_colormaps.setObjectName("discr_colormaps")
        self.gridLayout_2.addWidget(self.discr_colormaps, 5, 1, 1, 1)
        self.recontruction_frame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.recontruction_frame.setMinimumSize(QtCore.QSize(0, 250))
        self.recontruction_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.recontruction_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.recontruction_frame.setObjectName("recontruction_frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.recontruction_frame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.discr_image_id = QtWidgets.QPushButton(self.recontruction_frame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.discr_image_id.setFont(font)
        self.discr_image_id.setStyleSheet("QPushButton {\n"
"    border: none; /* Remove a borda */\n"
"    background-color: transparent; /* Fundo transparente */\n"
"    color: blue; /* Cor do texto em azul */\n"
"}\n"
"")
        self.discr_image_id.setObjectName("discr_image_id")
        self.gridLayout_3.addWidget(self.discr_image_id, 3, 3, 1, 1)
        self.discr_dimx = QtWidgets.QPushButton(self.recontruction_frame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.discr_dimx.setFont(font)
        self.discr_dimx.setStyleSheet("QPushButton {\n"
"    border: none; /* Remove a borda */\n"
"    background-color: transparent; /* Fundo transparente */\n"
"    color: blue; /* Cor do texto em azul */\n"
"}\n"
"")
        self.discr_dimx.setObjectName("discr_dimx")
        self.gridLayout_3.addWidget(self.discr_dimx, 5, 3, 1, 1)
        self.line_image_id = QtWidgets.QLineEdit(self.recontruction_frame)
        self.line_image_id.setMaximumSize(QtCore.QSize(150, 23))
        self.line_image_id.setObjectName("line_image_id")
        self.gridLayout_3.addWidget(self.line_image_id, 0, 1, 1, 1)
        self.discr_proj = QtWidgets.QPushButton(self.recontruction_frame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.discr_proj.setFont(font)
        self.discr_proj.setStyleSheet("QPushButton {\n"
"    border: none; /* Remove a borda */\n"
"    background-color: transparent; /* Fundo transparente */\n"
"    color: blue; /* Cor do texto em azul */\n"
"}\n"
"")
        self.discr_proj.setObjectName("discr_proj")
        self.gridLayout_3.addWidget(self.discr_proj, 4, 3, 1, 1)
        self.discr_slices = QtWidgets.QPushButton(self.recontruction_frame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.discr_slices.setFont(font)
        self.discr_slices.setStyleSheet("QPushButton {\n"
"    border: none; /* Remove a borda */\n"
"    background-color: transparent; /* Fundo transparente */\n"
"    color: blue; /* Cor do texto em azul */\n"
"}\n"
"")
        self.discr_slices.setObjectName("discr_slices")
        self.gridLayout_3.addWidget(self.discr_slices, 1, 3, 1, 1)
        self.discr_dimy = QtWidgets.QPushButton(self.recontruction_frame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.discr_dimy.setFont(font)
        self.discr_dimy.setStyleSheet("QPushButton {\n"
"    border: none; /* Remove a borda */\n"
"    background-color: transparent; /* Fundo transparente */\n"
"    color: blue; /* Cor do texto em azul */\n"
"}\n"
"")
        self.discr_dimy.setObjectName("discr_dimy")
        self.gridLayout_3.addWidget(self.discr_dimy, 6, 3, 1, 1)
        self.discr_pixelsize = QtWidgets.QPushButton(self.recontruction_frame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.discr_pixelsize.setFont(font)
        self.discr_pixelsize.setStyleSheet("QPushButton {\n"
"    border: none; /* Remove a borda */\n"
"    background-color: transparent; /* Fundo transparente */\n"
"    color: blue; /* Cor do texto em azul */\n"
"}\n"
"")
        self.discr_pixelsize.setObjectName("discr_pixelsize")
        self.gridLayout_3.addWidget(self.discr_pixelsize, 0, 3, 1, 1)
        self.line_proj = QtWidgets.QLineEdit(self.recontruction_frame)
        self.line_proj.setMaximumSize(QtCore.QSize(150, 23))
        self.line_proj.setObjectName("line_proj")
        self.gridLayout_3.addWidget(self.line_proj, 1, 1, 1, 1)
        self.line_dim_y = QtWidgets.QLineEdit(self.recontruction_frame)
        self.line_dim_y.setMinimumSize(QtCore.QSize(0, 23))
        self.line_dim_y.setMaximumSize(QtCore.QSize(150, 16777215))
        self.line_dim_y.setObjectName("line_dim_y")
        self.gridLayout_3.addWidget(self.line_dim_y, 4, 1, 1, 1)
        self.line_dim_x = QtWidgets.QLineEdit(self.recontruction_frame)
        self.line_dim_x.setMinimumSize(QtCore.QSize(0, 23))
        self.line_dim_x.setMaximumSize(QtCore.QSize(150, 16777215))
        self.line_dim_x.setObjectName("line_dim_x")
        self.gridLayout_3.addWidget(self.line_dim_x, 3, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.recontruction_frame)
        self.label_9.setMinimumSize(QtCore.QSize(80, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 4, 0, 1, 1)
        self.line_pixel = QtWidgets.QLineEdit(self.recontruction_frame)
        self.line_pixel.setMinimumSize(QtCore.QSize(0, 23))
        self.line_pixel.setMaximumSize(QtCore.QSize(150, 16777215))
        self.line_pixel.setObjectName("line_pixel")
        self.gridLayout_3.addWidget(self.line_pixel, 5, 1, 1, 1)
        self.line_slices = QtWidgets.QLineEdit(self.recontruction_frame)
        self.line_slices.setMinimumSize(QtCore.QSize(0, 23))
        self.line_slices.setMaximumSize(QtCore.QSize(150, 16777215))
        self.line_slices.setObjectName("line_slices")
        self.gridLayout_3.addWidget(self.line_slices, 6, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.recontruction_frame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 3, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.recontruction_frame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 6, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.recontruction_frame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 5, 0, 1, 1)
        self.label_image_id = QtWidgets.QLabel(self.recontruction_frame)
        self.label_image_id.setMinimumSize(QtCore.QSize(0, 36))
        self.label_image_id.setMaximumSize(QtCore.QSize(50, 36))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_image_id.setFont(font)
        self.label_image_id.setObjectName("label_image_id")
        self.gridLayout_3.addWidget(self.label_image_id, 0, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.recontruction_frame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.recontruction_frame, 19, 0, 8, 2)
        self.discr_cnoise = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.discr_cnoise.setMaximumSize(QtCore.QSize(30, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.discr_cnoise.setFont(font)
        self.discr_cnoise.setStyleSheet("QPushButton {\n"
"    border: none; /* Remove a borda */\n"
"    background-color: transparent; /* Fundo transparente */\n"
"    color: blue; /* Cor do texto em azul */\n"
"}\n"
"")
        self.discr_cnoise.setObjectName("discr_cnoise")
        self.gridLayout_2.addWidget(self.discr_cnoise, 14, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 2, 2)
        self.discr_colormaps_2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.discr_colormaps_2.setFont(font)
        self.discr_colormaps_2.setStyleSheet("QPushButton {\n"
"    border: none; /* Remove a borda */\n"
"    background-color: transparent; /* Fundo transparente */\n"
"    color: blue; /* Cor do texto em azul */\n"
"}\n"
"")
        self.discr_colormaps_2.setObjectName("discr_colormaps_2")
        self.gridLayout_2.addWidget(self.discr_colormaps_2, 3, 1, 1, 1)
        self.btn_open = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btn_open.setMinimumSize(QtCore.QSize(0, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_open.setFont(font)
        self.btn_open.setStyleSheet("QPushButton {\n"
"    background-color: #FFB62D;\n"
"    border-radius: 10px;\n"
"    border: 1px solid black;\n"
"}\n"
" \n"
"QPushButton:hover {\n"
"    background-color: #FFA500;\n"
"}\n"
" \n"
"QPushButton:pressed {\n"
"    background-color: #FFB62D;\n"
"    padding-left: 1px;\n"
"    padding-top: 1px;\n"
"}")
        self.btn_open.setObjectName("btn_open")
        self.gridLayout_2.addWidget(self.btn_open, 3, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_5.setStyleSheet("font: 87 16pt \"Segoe UI\";\n"
"font-weight: Bold")
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 2, 0, 1, 1)
        self.discr_recon_cpu = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.discr_recon_cpu.setFont(font)
        self.discr_recon_cpu.setStyleSheet("QPushButton {\n"
"    border: none; /* Remove a borda */\n"
"    background-color: transparent; /* Fundo transparente */\n"
"    color: blue; /* Cor do texto em azul */\n"
"}\n"
"")
        self.discr_recon_cpu.setObjectName("discr_recon_cpu")
        self.gridLayout_2.addWidget(self.discr_recon_cpu, 27, 1, 1, 1)
        self.discr_sharpness = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.discr_sharpness.setFont(font)
        self.discr_sharpness.setStyleSheet("QPushButton {\n"
"    border: none; /* Remove a borda */\n"
"    background-color: transparent; /* Fundo transparente */\n"
"    color: blue; /* Cor do texto em azul */\n"
"}\n"
"")
        self.discr_sharpness.setObjectName("discr_sharpness")
        self.gridLayout_2.addWidget(self.discr_sharpness, 16, 1, 1, 1)
        self.discr_recon_gpu = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.discr_recon_gpu.setFont(font)
        self.discr_recon_gpu.setStyleSheet("QPushButton {\n"
"    border: none; /* Remove a borda */\n"
"    background-color: transparent; /* Fundo transparente */\n"
"    color: blue; /* Cor do texto em azul */\n"
"}\n"
"")
        self.discr_recon_gpu.setObjectName("discr_recon_gpu")
        self.gridLayout_2.addWidget(self.discr_recon_gpu, 28, 1, 1, 1)
        self.discr_coronal = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.discr_coronal.setMaximumSize(QtCore.QSize(30, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.discr_coronal.setFont(font)
        self.discr_coronal.setStyleSheet("QPushButton {\n"
"    border: none; /* Remove a borda */\n"
"    background-color: transparent; /* Fundo transparente */\n"
"    color: blue; /* Cor do texto em azul */\n"
"}\n"
"")
        self.discr_coronal.setObjectName("discr_coronal")
        self.gridLayout_2.addWidget(self.discr_coronal, 2, 7, 1, 1)
        self.discr_sagital = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.discr_sagital.setMaximumSize(QtCore.QSize(30, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.discr_sagital.setFont(font)
        self.discr_sagital.setStyleSheet("QPushButton {\n"
"    border: none; /* Remove a borda */\n"
"    background-color: transparent; /* Fundo transparente */\n"
"    color: blue; /* Cor do texto em azul */\n"
"}\n"
"")
        self.discr_sagital.setObjectName("discr_sagital")
        self.gridLayout_2.addWidget(self.discr_sagital, 2, 10, 1, 1)
        self.radio_sagital = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.radio_sagital.setFont(font)
        self.radio_sagital.setObjectName("radio_sagital")
        self.gridLayout_2.addWidget(self.radio_sagital, 2, 9, 1, 1)
        self.label_kV = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_kV.setFont(font)
        self.label_kV.setObjectName("label_kV")
        self.gridLayout_2.addWidget(self.label_kV, 28, 16, 1, 2)
        self.label_Z = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_Z.setFont(font)
        self.label_Z.setObjectName("label_Z")
        self.gridLayout_2.addWidget(self.label_Z, 28, 14, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1307, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CT Industrial Visualizer"))
        self.btn_save_image.setText(_translate("MainWindow", "Save Image"))
        self.btn_rot.setText(_translate("MainWindow", "Rotate"))
        self.label_6.setText(_translate("MainWindow", "Tomographic views"))
        self.btn_colormap.setText(_translate("MainWindow", "Colormaps"))
        self.btn_clear.setText(_translate("MainWindow", "Clear"))
        self.btn_roi2.setText(_translate("MainWindow", "ROI 2"))
        self.btn_hist.setText(_translate("MainWindow", "Histogram"))
        self.btn_roi1.setText(_translate("MainWindow", "ROI 1"))
        self.slider_sharp_name.setText(_translate("MainWindow", "Improve Sharpness"))
        self.label_2.setText(_translate("MainWindow", "Reconstruction"))
        self.btn_iq.setText(_translate("MainWindow", "Calculate CNR - SNR"))
        self.btn_flat.setText(_translate("MainWindow", "Apply Flat Field"))
        self.label_4.setText(_translate("MainWindow", "Image quality"))
        self.label_3.setText(_translate("MainWindow", "Filters"))
        self.slider_sharp_name_2.setText(_translate("MainWindow", "Reduce noise"))
        self.btn_rec_cpu.setText(_translate("MainWindow", "Reconstruction via CPU"))
        self.btn_rec_gpu.setText(_translate("MainWindow", "Reconstruction via GPU"))
        self.label_value.setText(_translate("MainWindow", "Pixel Value:"))
        self.label_foco.setText(_translate("MainWindow", "Foco:"))
        self.label_mean.setText(_translate("MainWindow", "Mean:"))
        self.label_mAs.setText(_translate("MainWindow", "mAs:"))
        self.label_std.setText(_translate("MainWindow", "STD:"))
        self.radio_axial.setText(_translate("MainWindow", "Axial"))
        self.label_sum.setText(_translate("MainWindow", "Sum:"))
        self.discr_axial.setText(_translate("MainWindow", "?"))
        self.radio_coronal.setText(_translate("MainWindow", "Coronal"))
        self.label_max.setText(_translate("MainWindow", "Max:"))
        self.label_min.setText(_translate("MainWindow", "Min:"))
        self.discr_cnr_snr.setText(_translate("MainWindow", "?"))
        self.discr_flatfield.setText(_translate("MainWindow", "?"))
        self.discr_roi2.setText(_translate("MainWindow", "?"))
        self.discr_roi1.setText(_translate("MainWindow", "?"))
        self.discr_histagram.setText(_translate("MainWindow", "?"))
        self.discr_colormaps_3.setText(_translate("MainWindow", "?"))
        self.discr_rotate.setText(_translate("MainWindow", "?"))
        self.discr_colormaps.setText(_translate("MainWindow", "?"))
        self.discr_image_id.setText(_translate("MainWindow", "?"))
        self.discr_dimx.setText(_translate("MainWindow", "?"))
        self.discr_proj.setText(_translate("MainWindow", "?"))
        self.discr_slices.setText(_translate("MainWindow", "?"))
        self.discr_dimy.setText(_translate("MainWindow", "?"))
        self.discr_pixelsize.setText(_translate("MainWindow", "?"))
        self.label_9.setText(_translate("MainWindow", "Dim Y:"))
        self.label_8.setText(_translate("MainWindow", "Dim X:"))
        self.label_11.setText(_translate("MainWindow", "#Slices:"))
        self.label_10.setText(_translate("MainWindow", "Pixel size (mm):"))
        self.label_image_id.setText(_translate("MainWindow", "Image:"))
        self.label_7.setText(_translate("MainWindow", "Projections:"))
        self.discr_cnoise.setText(_translate("MainWindow", "?"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><img src=\":/Logo/QT designer assets/logo-ibti SVG.png\"/></p></body></html>"))
        self.discr_colormaps_2.setText(_translate("MainWindow", "?"))
        self.btn_open.setText(_translate("MainWindow", "Open"))
        self.label_5.setText(_translate("MainWindow", "Controls"))
        self.discr_recon_cpu.setText(_translate("MainWindow", "?"))
        self.discr_sharpness.setText(_translate("MainWindow", "?"))
        self.discr_recon_gpu.setText(_translate("MainWindow", "?"))
        self.discr_coronal.setText(_translate("MainWindow", "?"))
        self.discr_sagital.setText(_translate("MainWindow", "?"))
        self.radio_sagital.setText(_translate("MainWindow", "Sagital"))
        self.label_kV.setText(_translate("MainWindow", "KV:"))
        self.label_Z.setText(_translate("MainWindow", "Z:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
